### ISSUE TITLE
Supply Crates: Warzone Envoys

### ISSUE THREAD

**Issue by Morphiee** [SalvosGG/issue-tracker#11]
Here we will nail down everything needed for supply drops/envoys that appear in the spawn. We will use this as a sort of suggestion list so we can update it to the best of our ability. Please use the format below.

**EXAMPLE FORMAT:** 
Tier: (1-3)
Reward: (These have to be dropable items)

Please do **NOT** write multiple comments on this. If you want to edit multiple things please put them in one message. Please use the above format to the best of your ability. DO NOT use this issue as a discussion section. Discussions should happen on discord.

**Comment by craddd** [comment]
Tier: 1
 - remove enchant books from this tier, the t1 enchants are worthless even to someone who *just* started
 - add a chance for phantom membrane
 - add gunpowder as a possible drop in a quantity of 8x or something
 - chance for emerald block 1x
 - chance for ender pearl 1x
 - chance for xp pots x16
 Tier: 2
- replace the enchant books currently available from t2 and replace with the ones available in t3 currently, max level vanilla enchants
- increase chance of phantom membrane drop and quantity from 2x to 4x
- add with skeleton skulls, low chance and 1x
- add nether wart, average chance and 8x
- chance for emerald block 2x
- chance for ender pearls 2x
- chance for xp pots x32
Tier: 3
- *low* chance for a random CE, no vanilla enchant possibility
- wither skeleton skulls at a slightly higher rate then t2
- chance for netherite scraps 2x
- chance for gold blocks 2x
- chance for diamond block 1x
- chance for emerald block 4x
- chance for ender pearls 4x
- chance for shulker shell 1x
- chance for xp pots x64
- chance for anvil 1x
- chance for etable 1x and bookshelves 8x

**Comment by Morphiee** [comment]
- Added an envoy flare to the vote crate. Right-clicking this flare will start a supply crate event within the warzone.
- Removed naming of all items so they stack with others for ease of storage. :)
- Change message colors to match our server more.

Updated Crate Tier Rewards:
Tier I (All Items set to 30% Drop Chance)
- x2 Phantom Membrane
- x8 Gunpowder
- x1 Emerald Block
- x5 Glow Ink Sac
- x3 Golden Apple
- x3 Ender Pearl
- x16 EXP Bottles
- x4 Slime Balls
- x16 Raw Copper
- x16 Raw Iron
- x16 Raw Gold
- x32 Coal
- x5 Soul Torch

Tier II (All Items set to 30% drop chance unless stated otherwise.)
- x4 Phantom Membrane
- x6 Golden Apple
- x1 Wither Skeleton Skull (15%)
- x4 Diamond
- x8 Nether Wart
- x2 Emerald Block
- x6 Ender Pearl
- x3 Glistering Melon Slice
- x3 Golden Carrot
- x1 Axolotl Spawn Egg
- x1 Villager Spawn Egg (15%)
- x1 Knockback II Book
- x1 Sharpness IV Book
- x1 Power IV Book
- x1 Fortune III Book (15%)
- x1 Unbreaking III Book (15%)
- x1 Silktouch Book (15%)

Tier III (All Items set to 30% drop chance unless stated otherwise.)
- x1 Wither Skeleton Skull
- x2 Netherite Ingot
- x1 Normal Cubelet (Cosmetic Token)
- x1 Super Cubelet (Cosmetic Token)
- x1 Money Booster 3
- x1 Money Booster 4
- x1 Money Booster 5
- x1 Enchanting Package: Enchantment Table, x8 Bookshelf, x16 Lapis Block
- x1 Flytime Voucher [30 Mins]
- x1 Flytime Voucher [60 Mins]
- x1 Gravestone
- x10 Tokens
- x15 Tokens
- x25 Tokens
- x1 Shop Advertisement Token [60 Mins]
- x1 Random Common Custom Enchantment (30%)
- x1 Random Rare Custom Enchantment (25%)
- x1 Random Epic Custom Enchantment (15%)
