### ISSUE TITLE
Salvos Questlines

### ISSUE THREAD

**Issue by Morphiee** [SalvosGG/issue-tracker#13]
We **CAN** add more questlines **BUT** these are limited slightly. Please refer to [this](https://documentation.smcdevelopments.com/supreme-survival/supreme-plugins/supremequests) documentation on the quest plugin.

Take note of the **_"Task types"_** section that dictate what the quest task is.

**EXAMPLE FORMAT:** (this format is a base one you will need to change it based on the task type)
Quest Task Type: Kill Mob
Kill 10 Wither Skeletons

Quest rewards will generally stay the same. They are all similar and quests are mainly used for leveling up. (that is the main reward itself.)

Please do **NOT** write multiple comments on this. If you want to edit multiple things please put them in one message. Please use the above format to the best of your ability. **DO NOT** use this issue as a discussion section. Discussions should happen on discord.

**Comment by craddd** [comment]
Quest Task Type: Kill Mob
- Kill 1 Evoker (scaled similarly to ghasts)
- Kill 5 Ravengers (scaled similarly to hoglins)
- Kill 1 Wither (scaled similar to ghasts)
- Kill 1 Ender Dragon (scaled similar to ghasts)
- Kill 5 Shulkers (scaled similar to hoglins)
- Kill 1 Elder Guardian (scaled similar to ghasts)
- Kill 5 Dolphins (scaled similar to hoglins)
Rewards resembling the standard rewards for this quest type
Quest Task Type: Gathering
- Gather 25 String (scaled similar to arrows)
- Move chorus fruit to the farming section
- Remove the kelp line from gathering, its already in the farming section
- Gather 25 Gunpowder (scaled similar to arrows)
