### ISSUE TITLE
Crate animations too long

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#16]
The animation when you open a crate is quite long. Opening a crate should be a reward, not a punishment! ^^ (couldn't resist)

**Comment by Morphiee** [comment]
I understand; Honestly I want to change the crate animation to nothing. Just instant reward. I will add this to our to do list. Thank you obs.

**Comment by Morphiee** [comment]
Animations removed; It will now instant give rewards with a hologram above the crate and chat message to indicate the reward recieved.
