### ISSUE TITLE
Entity Cramming

### ISSUE THREAD

**Issue by Morphiee** [SalvosGG/issue-tracker#17]
The entity cramming limit is way too low. 8-10 mobs max before it starts killing them off. Look into raising the limit for specific mob types:

SHEEP
COW
CHICKEN
PIG
ZOMBIE
SKELETON
SPIDER (Slightly)
BLAZE (VERY Slightly)
MOOSHROOM

Side Note: I wonder if this is chunk based or block based. Spreading out the animals may change the how it is limited.

**Comment by CupsOhJoe** [comment]
This is currently set in a gamerule

**Comment by Morphiee** [comment]
Ah well we need to remove it then and use spigot/paper yml for entity cramming. They can only have 8-10 mobs rn and that is way too little for how much other servers can handle. I say we bump it to like 25-30 for passives and 15-20 for hostiles.

Not to much of a buff but enough for it to mater when making farms for mobs.

**Comment by Morphiee** [comment]
Entity cramming was set to 12 (default is 24 for Minecraft) I upped cramming to 20 (to still help with lag) I'm able to get around 95 mobs in a hole (after I spammed and some died due to cramming)

I'm sure up to 100 mobs ish should be fine.
