### ISSUE TITLE
/warp end takes you to overworld

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#18]
/warp end takes you to x=42.5 y=15 z=62.5 in the overworld

I'm not lvl 30 yet so should normally not have access. Don't know for lvl30+

**Comment by Morphiee** [comment]
This is an odd one. Warp has been removed as it was teleporting players to the bottom of the spawn world. (not overworld spawn itself)

Players should use `/rtp` OR `/warps -> worlds -> end` for accessing the end. We will be trying to figure out portals working but for now, they do not. Thanks for the catch Obs.
