### ISSUE TITLE
/job does not pay anything when mining deepslate 

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#22]
In the earnings of /job it mentions some blocks with pay out, but nothing is payed when you main them.
Mined 20 deepslate that normally yields 0.06$, but after mining more than 20 nothing gets payed out. 
Tried logging out and back in, no change. Farming and other mining payouts still seem to work.

So far all 1.18 blocks I think. Coincidence?

List of blocks impacted (the ones I found so far):
deepslate 0.06$
tuff 7.5$ (seems high as it is easy to get in high quantities)
dripstone 10$ (seems high)
calcite 5$
smooth basalt 5$

**Comment by Morphiee** [comment]
Added the below blocks to the mining job payout:

    deepslate_coal_ore:
      income: 3
      points: 2
      experience: 3
    deepslate_copper_ore:
      income: 1.5
      points: 1
      experience: 1.5
    deepslate_redstone_ore:
      income: 2.5
      points: 2
      experience: 2
    deepslate_iron_ore:
      income: 3.5
      points: 3
      experience: 2
    deepslate_gold_ore:
      income: 5
      points: 4
      experience: 2
    deepslate_lapis_ore:
      income: 7.5
      points: 6
      experience: 2
    deepslate_diamond_ore:
      income: 10
      points: 9
      experience: 6
    deepslate_emerald_ore:
      income: 11
      points: 6
      experience: 6
    CALCITE:
      income: 0.15
      points: 0.1
      experience: 0.2
    TUFF:
      income: 0.15
      points: 0.1
      experience: 0.2
    DRIPSTONE_BLOCK:
      income: 0.15
      points: 0.1
      experience: 0.2
    POINTED_DRIPSTONE:
      income: 0.15
      points: 0.1
      experience: 0.2
    SMOOTH_BASALT:
      income: 0.15
      points: 0.1
      experience: 0.2
