### ISSUE TITLE
PyroFishing biome corrections/balancing

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#23]
Some fish are impossible to catch or too hard to get for their tier (just my opinion). List below with the biomes they appear in.
 
Bronze:
Sardine (The End)
Pike (The End, End Barrens, End Highlands, End Midlands, Eroded Badlands)
Angelfish (no biomes, cannot be caught!)

Gold:
Lava Eel (Crimson Forest)
Serina (The End)

Diamond:
Grand SwordFish (Crimson Forest)
Great Fairy Fish (no biomes, cannot be caught!)
Void Salmon (The Void)

Platinum:
Rouge Fish (Crimson Forest, The End)
Death Manta (Crimson Forest)

Note: The End is the biome for the main island only, doesn't appear anywhere else. Not sure there is water there (haven't seen the End yet)

**Comment by NotoriousRogue** [comment]
I do believe we’re actually gonna be building some sort of fishing spot within the end so catching these fish will be a lot easier. Sorta like we have with the fishing island.

**Comment by Koekie78** [comment]
Just don't forget the few in crimson forrest then :)

**Comment by UnAlguien** [comment]
ik the nether is impossible but does placed water not work for the end?
