### ISSUE TITLE
[item] needs looking at

### ISSUE THREAD

**Issue by ipodfleajr** [SalvosGG/issue-tracker#27]
doing [item] will return in plain white text normal items you are holding just without the custom enchants. 
doing [i] returns an error.  
doing [item] with a server item (ex. vote key, supply box items) works just fine.

**Comment by Morphiee** [comment]
The item has been fixed. It appears it was using a chat control version when we swapped to that chat management plugin. All of the reported now works as well as being able to do the following.

[item] | [i]
[money] | [m] | [bal]
[inv] | [inventory]
