### ISSUE TITLE
Battlepass: some quests not working

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#29]
Week 2: Birch, dark oak and spruce quests not working (probably the same for jungle). However, oak is working!

Week 4: When crafting 16 cobblestone wall with the stonecutter they don't count for the battlepass quest. With /workbench or a crafting table they are counted correctly.

**Comment by Morphiee** [comment]
Closing this as battle pass was never configured and I don't think we will be using it for launch.
