### ISSUE TITLE
/lands: not possible to create areas within your land

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#31]
When you try to create an area inside your land, you get following error:
This land reached their maximum amount of 0 areas

Maximum allowed lands in an area is set to zero. Increasing it would encourage player interactions and reduce drama because you can trust people in only a part of your land.

**Comment by Morphiee** [comment]
At default, users can now create up to 10 sub-areas per land. We can add ways to get more areas in the future if needed.
