### ISSUE TITLE
Level Tags: Need some creative minds.

### ISSUE THREAD

**Issue by Morphiee** [SalvosGG/issue-tracker#35]
For every 10 levels completed the player will earn a tag. They currently are only symbols and I feel as if we should change them to better fit our server. Now we used mythological gods/goddesses for the donor rank names. I figured we would want to keep that theme going. If you are up to it please feel free to suggest names for the level tags.

Example: Medusa

**Comment by Shinovz** [comment]
Shinovz

**Comment by UnAlguien** [comment]
thank you shinovz

**Comment by Morphiee** [comment]
Minotaur
Sirens
Hydra
Sphinx

**Comment by Morphiee** [comment]
Phoenix 
Cyclopes
Cerberus
Fury
Kraken
Gorgon
Basilisk
Triton
Chimera

**Comment by UnAlguien** [comment]
Achilles
Narcissus
snake hair stone lady i forgor

**Comment by Shinovz** [comment]
> Achilles
> Narcissus
> snake hair stone lady i forgor

I think that’s medusa

**Comment by UnAlguien** [comment]
Icarus
Pandora
UnAdmin
Hercules

**Comment by craddd** [comment]
optons
not in order:
Harpy (bird women)
Siren (evil mermaids)
Gorgons (medusa and her sisters)
Typhon (the king of monsters)
Echidna (the queen of monsters)
Sphinx (ye they're in greek mythology too)
Giants (big mfs)
Cyclops (mfs from odysseus)
Chimera (goat/lion/snake threesome offspring)
Hydra (dragon with extra heads)
Cerberus (three headed devil dog guarding hell)
Minotaur (moo)
Colchian dragon (this one is complicated but basically a big fire-breathing snake that guarded a fleece)

**Comment by UnAlguien** [comment]
stop stealing suggestions dickhead

**Comment by kulaid** [comment]
options
in order:
Harpy (bird women)
Siren (evil mermaids)
Gorgons (medusa and her sisters)
Typhon (the king of monsters)
Echidna (the queen of monsters)
Sphinx (ye they're in greek mythology too)
Giants (big mfs)
Cyclops (mfs from odysseus)
Chimera (goat/lion/snake threesome offspring)
Hydra (dragon with extra heads)
Cerberus (three headed devil dog guarding hell)
Minotaur (moo)
Colchian dragon (this one is complicated but basically a big fire-breathing snake that guarded a fleece)
